name: Cesium Unreal Release Notifier

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  check_for_new_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download last checked release tag from previous run
        uses: dawidd6/action-download-artifact@v2
        id: download_artifact_step
        with:
          workflow: notify-cesium-release.yml
          name: last-checked-release
          path: .
          if_no_artifact_found: ignore

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios nodemailer

      - name: Check for new release and send notification
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: node script.js

      - name: Upload last checked release tag
        uses: actions/upload-artifact@v4
        with:
          name: last-checked-release
          path: last_checked_release.txt
          if-no-files-found: ignore
        id: upload_artifact_step
